TAG
WIP

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>

diff --git a/.github/workflows/gating.yaml b/.github/workflows/gating.yaml
--- a/.github/workflows/gating.yaml
+++ b/.github/workflows/gating.yaml
@@ -46,21 +46,49 @@ jobs:
           python src/ipa-tuura/manage.py test
 
   build:
-    name: run pre-commit hook but rather build image --- TBA
     runs-on: ubuntu-latest
+    env:
+      IMAGE_TAG: ${{ github.event.number || github.ref_name  }}
+
+    name: build the docker image
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-python@v4
+      - name: Checkout the repository
+        uses: actions/checkout@v3
+
+      - name: Set up QEMU for docker
+        uses: docker/setup-qemu-action@v2
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Print IMAGE_TAG to be used
+        run: echo "${{ env.IMAGE_TAG }}"
+
+      - name: Login to quay.io
+        uses: docker/login-action@v2
         with:
-          python-version: "3.10"
-      - uses: pre-commit/action@v3.0.0
+          registry: quay.io
+          username: ${{ secrets.REGISTRY_USERNAME }}
+          password: ${{ secrets.REGISTRY_TOKEN }}
+
+      - name: Build and push the image with given tag
+        uses: docker/build-push-action@v3
+        with:
+          context: ./src
+          file: ./src/Containerfile
+          push: true
+          tags: "quay.io/idmops/${{ github.event.repository.name }}:${{github.event.number}}"
 
   test:
     name: test the built image
     runs-on: ubuntu-latest
     container:
-      image: "quay.io/idmops/fedora:${{github.event.number}}"
-    needs: [pre-commit, build, test-on-ubuntu]
+      image: "quay.io/idmops/${{ github.event.repository.name }}:${{ github.event.number || github.ref_name }}"
+    needs: [pre-commit, test-on-ubuntu, build]
+
     steps:
       - name: Display OS version
         run: cat /etc/redhat-release || uname -a
+
+      - name: Print PULL_IMAGE to be used
+        run: file /ipa-tuura/manage.py || echo "/ipa-tuura/manage.py not found"
